Corrupted readable
avast/pelib pull request #5
Opened 2019-01-14 13:49 UTC by ladislav-zezula

Added check for files that are cut but still loadable/executable

2019-01-16 09:21 UTC, s3rvac commented
This PR is part of https://github.com/avast-tl/retdec/issues/463 (we will have to update the version of https://github.com/avast-tl/pelib in RetDec after this PR is merged into `master`).

2019-01-17 06:25 UTC, s3rvac requested changes
Thank you for the improvement! :+1: I only have several suggestions towards the code.

2019-01-17 06:25 UTC, s3rvac commented on include/pelib/PeHeader.h
> +			if (vIshdCurr.size() > 0)
Tip: `vIshdCurr` is `std::vector`, so instead of
```cpp
if (vIshdCurr.size() > 0)
```
you can write
```cpp
if (!vIshdCurr.empty())
```
which is what you are actually testing + it reads like an English sentence (_if the container is not empty_).

2019-01-17 06:25 UTC, s3rvac commented on include/pelib/PeHeader.h
> +				PELIB_IMAGE_SECTION_HEADER & lastSection = vIshdCurr[vIshdCurr.size() - 1];
Tip: Instead of `vIshdCurr[vIshdCurr.size() - 1]`, you can simply write `vIshdCurr.back()`, which gives you the last element in the vector without a need to manually compute the last index (see [std::vector::back()](https://en.cppreference.com/w/cpp/container/vector/back)).

2019-01-17 06:25 UTC, s3rvac commented on include/pelib/PeHeader.h
> +
Nitpick: Is this whitespace change needed?

2019-01-17 06:25 UTC, s3rvac commented on src/pelib/PeLibAux.cpp
> +
Nitpick: Is this newly added empty line needed?

2019-01-17 07:35 UTC, ladislav-zezula commented
Fixed in commit https://github.com/avast-tl/pelib/commit/d1a7e06afb08cadacf0fd88ed434a47a7bb43d59

2019-01-17 08:07 UTC, s3rvac approved these changes
Great, thank you :+1:  I will merge the PR and use it in RetDec.

2019-01-17 09:51 UTC, merged